### ISSUE TITLE
urllib.encode deprecated in python3

### ISSUE THREAD

**Issue by feclist** [paste/ost-kit-python#1]
First of all, thanks for making this open source OST API SDK :))

The project we're working on is built in Python 3 and we found that once a signed request is about to be posted the urllib.encode is called which got changed to urllib.parse.encode in Python 3. I can make a fork and change this line of code to suit my needs, but I figured I might as well raise this issue.

**Comment by aoxborrow** [comment]
Thanks for letting me know! I was just about to start using this with a new python3 project, and I was wondering how compatible it was. I would like to make it 2/3 compatible since my older project will stay in Python 2 for now. I should be able to look at this tonight. If you get to it first I would be happy to merge in a pull request.

**Comment by feclist** [comment]
In the __init__.py file on line 86 I replaced the entire thing with:
`signature = hmac.new(self.api_secret.encode(), msg=string_to_sign.encode('utf-8'), digestmod=hashlib.sha256).hexdigest()`

and line 80 replaced with:
`querystring = urllib.parse.urlencode(sorted(params.items()))`

Not the most clean fix but this way it works with python3 :)

**Comment by aoxborrow** [comment]
version 0.0.3 released to pypi with python3 compatibility, thanks @feclist !
